Class {
	#name : 'ORActionMoveTPackage',
	#superclass : 'ORActionMoveNamedEntity',
	#instVars : [
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionMoveTPackage >> childEntities [ ^childEntities
]

{ #category : 'accessing' }
ORActionMoveTPackage >> childEntities: aValue [ childEntities := aValue
]

{ #category : 'accessing' }
ORActionMoveTPackage >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionMoveTPackage >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionMoveTPackage >> name [ ^name
]

{ #category : 'accessing' }
ORActionMoveTPackage >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionMoveTPackage >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionMoveTPackage >> sourceAnchor: aValue [ sourceAnchor := aValue
]
