Class {
	#name : 'ORActionRemoveTImplementation',
	#superclass : 'ORActionRemove',
	#instVars : [
		'implementingClass',
		'interface',
		'next',
		'previous',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveTImplementation >> implementingClass [ ^implementingClass
]

{ #category : 'accessing' }
ORActionRemoveTImplementation >> implementingClass: aValue [ implementingClass := aValue
]

{ #category : 'accessing' }
ORActionRemoveTImplementation >> interface [ ^interface
]

{ #category : 'accessing' }
ORActionRemoveTImplementation >> interface: aValue [ interface := aValue
]

{ #category : 'accessing' }
ORActionRemoveTImplementation >> next [ ^next
]

{ #category : 'accessing' }
ORActionRemoveTImplementation >> next: aValue [ next := aValue
]

{ #category : 'accessing' }
ORActionRemoveTImplementation >> previous [ ^previous
]

{ #category : 'accessing' }
ORActionRemoveTImplementation >> previous: aValue [ previous := aValue
]

{ #category : 'accessing' }
ORActionRemoveTImplementation >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveTImplementation >> sourceAnchor: aValue [ sourceAnchor := aValue
]
