Class {
	#name : 'ORActionMoveTMethod',
	#superclass : 'ORActionMoveNamedEntity',
	#instVars : [
		'parentType',
		'signature',
		'declaredType',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionMoveTMethod >> accesses [ ^accesses
]

{ #category : 'accessing' }
ORActionMoveTMethod >> accesses: aValue [ accesses := aValue
]

{ #category : 'accessing' }
ORActionMoveTMethod >> declaredType [ ^declaredType
]

{ #category : 'accessing' }
ORActionMoveTMethod >> declaredType: aValue [ declaredType := aValue
]

{ #category : 'accessing' }
ORActionMoveTMethod >> implicitVariables [ ^implicitVariables
]

{ #category : 'accessing' }
ORActionMoveTMethod >> implicitVariables: aValue [ implicitVariables := aValue
]

{ #category : 'accessing' }
ORActionMoveTMethod >> incomingInvocations [ ^incomingInvocations
]

{ #category : 'accessing' }
ORActionMoveTMethod >> incomingInvocations: aValue [ incomingInvocations := aValue
]

{ #category : 'accessing' }
ORActionMoveTMethod >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionMoveTMethod >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionMoveTMethod >> localVariables [ ^localVariables
]

{ #category : 'accessing' }
ORActionMoveTMethod >> localVariables: aValue [ localVariables := aValue
]

{ #category : 'accessing' }
ORActionMoveTMethod >> name [ ^name
]

{ #category : 'accessing' }
ORActionMoveTMethod >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionMoveTMethod >> outgoingInvocations [ ^outgoingInvocations
]

{ #category : 'accessing' }
ORActionMoveTMethod >> outgoingInvocations: aValue [ outgoingInvocations := aValue
]

{ #category : 'accessing' }
ORActionMoveTMethod >> outgoingReferences [ ^outgoingReferences
]

{ #category : 'accessing' }
ORActionMoveTMethod >> outgoingReferences: aValue [ outgoingReferences := aValue
]

{ #category : 'accessing' }
ORActionMoveTMethod >> parameters [ ^parameters
]

{ #category : 'accessing' }
ORActionMoveTMethod >> parameters: aValue [ parameters := aValue
]

{ #category : 'accessing' }
ORActionMoveTMethod >> parentType [ ^parentType
]

{ #category : 'accessing' }
ORActionMoveTMethod >> parentType: aValue [ parentType := aValue
]

{ #category : 'accessing' }
ORActionMoveTMethod >> signature [ ^signature
]

{ #category : 'accessing' }
ORActionMoveTMethod >> signature: aValue [ signature := aValue
]

{ #category : 'accessing' }
ORActionMoveTMethod >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionMoveTMethod >> sourceAnchor: aValue [ sourceAnchor := aValue
]
