Class {
	#name : 'ORActionMoveTClass',
	#superclass : 'ORActionMove',
	#instVars : [
		'isAbstract',
		'isClassSide',
		'isFinal',
		'interfaceImplementations',
		'receivingInvocations',
		'attributes',
		'comments',
		'superInheritances',
		'subInheritances',
		'visibility',
		'incomingImports',
		'parentPackage',
		'imports'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}
