Class {
	#name : 'ORActionMoveJavaMethod',
	#superclass : 'ORActionMoveTMethod',
	#instVars : [
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'isSynchronized',
		'isAbstract',
		'isClassSide',
		'isFinal',
		'kind',
		'visibility',
		'incomingImports',
		'comments',
		'caughtExceptions',
		'declaredExceptions',
		'thrownExceptions'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionMoveJavaMethod >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> caughtExceptions [ ^caughtExceptions
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> caughtExceptions: aValue [ caughtExceptions := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> declaredExceptions [ ^declaredExceptions
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> declaredExceptions: aValue [ declaredExceptions := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> isAbstract [ ^isAbstract
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> isAbstract: aValue [ isAbstract := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> isSynchronized [ ^isSynchronized
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> isSynchronized: aValue [ isSynchronized := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> kind [ ^kind
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> kind: aValue [ kind := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> thrownExceptions [ ^thrownExceptions
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> thrownExceptions: aValue [ thrownExceptions := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> types [ ^types
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionMoveJavaMethod >> visibility: aValue [ visibility := aValue
]
