Class {
	#name : 'ORActionRenameTPrimitiveType',
	#superclass : 'ORActionRenameNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRenameTPrimitiveType >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionRenameTPrimitiveType >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionRenameTPrimitiveType >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRenameTPrimitiveType >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRenameTPrimitiveType >> name [ ^name
]

{ #category : 'accessing' }
ORActionRenameTPrimitiveType >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRenameTPrimitiveType >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRenameTPrimitiveType >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRenameTPrimitiveType >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionRenameTPrimitiveType >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionRenameTPrimitiveType >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionRenameTPrimitiveType >> typedEntities: aValue [ typedEntities := aValue
]
