"
I add a new FamixTParameter in an OrionModel.
I need the following properties :
- `declaredType`
- `isFinal`
- `isStub`
- `name`
- `parentBehaviouralEntity`
"
Class {
	#name : 'ORActionAddTParameter',
	#superclass : 'ORActionAddTNamedEntity',
	#instVars : [
		'name',
		'isFinal',
		'parentBehaviouralEntity',
		'isStub',
		'declaredType'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}
