Class {
	#name : 'ORActionRenameTException',
	#superclass : 'ORActionRenameNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRenameTException >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionRenameTException >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> catchingEntities [ ^catchingEntities
]

{ #category : 'accessing' }
ORActionRenameTException >> catchingEntities: aValue [ catchingEntities := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionRenameTException >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> declaringEntities [ ^declaringEntities
]

{ #category : 'accessing' }
ORActionRenameTException >> declaringEntities: aValue [ declaringEntities := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionRenameTException >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRenameTException >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionRenameTException >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> name [ ^name
]

{ #category : 'accessing' }
ORActionRenameTException >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionRenameTException >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRenameTException >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionRenameTException >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionRenameTException >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> throwingEntities [ ^throwingEntities
]

{ #category : 'accessing' }
ORActionRenameTException >> throwingEntities: aValue [ throwingEntities := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionRenameTException >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionRenameTException >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionRenameTException >> typedEntities: aValue [ typedEntities := aValue
]
