Class {
	#name : 'ORActionRemoveTAnnotationType',
	#superclass : 'ORActionRemove',
	#instVars : [
		'annotationTypesContainer'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveTAnnotationType >> annotationTypesContainer [ ^annotationTypesContainer
]

{ #category : 'accessing' }
ORActionRemoveTAnnotationType >> annotationTypesContainer: aValue [ annotationTypesContainer := aValue
]

{ #category : 'accessing' }
ORActionRemoveTAnnotationType >> instances [ ^instances
]

{ #category : 'accessing' }
ORActionRemoveTAnnotationType >> instances: aValue [ instances := aValue
]
