Class {
	#name : 'ORActionRemoveTException',
	#superclass : 'ORActionRemoveNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveTException >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionRemoveTException >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> catchingEntities [ ^catchingEntities
]

{ #category : 'accessing' }
ORActionRemoveTException >> catchingEntities: aValue [ catchingEntities := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionRemoveTException >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> declaringEntities [ ^declaringEntities
]

{ #category : 'accessing' }
ORActionRemoveTException >> declaringEntities: aValue [ declaringEntities := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionRemoveTException >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveTException >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionRemoveTException >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> name [ ^name
]

{ #category : 'accessing' }
ORActionRemoveTException >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionRemoveTException >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveTException >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionRemoveTException >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionRemoveTException >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> throwingEntities [ ^throwingEntities
]

{ #category : 'accessing' }
ORActionRemoveTException >> throwingEntities: aValue [ throwingEntities := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionRemoveTException >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionRemoveTException >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionRemoveTException >> typedEntities: aValue [ typedEntities := aValue
]
