Class {
	#name : 'ORActionMoveTPrimitiveType',
	#superclass : 'ORActionMoveNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionMoveTPrimitiveType >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionMoveTPrimitiveType >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionMoveTPrimitiveType >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionMoveTPrimitiveType >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionMoveTPrimitiveType >> name [ ^name
]

{ #category : 'accessing' }
ORActionMoveTPrimitiveType >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionMoveTPrimitiveType >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionMoveTPrimitiveType >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionMoveTPrimitiveType >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionMoveTPrimitiveType >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionMoveTPrimitiveType >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionMoveTPrimitiveType >> typedEntities: aValue [ typedEntities := aValue
]
