Class {
	#name : 'ORActionRenameTEnum',
	#superclass : 'ORActionRenameNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRenameTEnum >> enumValues [ ^enumValues
]

{ #category : 'accessing' }
ORActionRenameTEnum >> enumValues: aValue [ enumValues := aValue
]

{ #category : 'accessing' }
ORActionRenameTEnum >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionRenameTEnum >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionRenameTEnum >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRenameTEnum >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRenameTEnum >> name [ ^name
]

{ #category : 'accessing' }
ORActionRenameTEnum >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRenameTEnum >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRenameTEnum >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRenameTEnum >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionRenameTEnum >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionRenameTEnum >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionRenameTEnum >> typedEntities: aValue [ typedEntities := aValue
]
