Class {
	#name : 'ORActionRemoveTUnknownVariable',
	#superclass : 'ORActionRemoveNamedEntity',
	#instVars : [
		'isStub',
		'sourceAnchor',
		'declaredType'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveTUnknownVariable >> declaredType [ ^declaredType
]

{ #category : 'accessing' }
ORActionRemoveTUnknownVariable >> declaredType: aValue [ declaredType := aValue
]

{ #category : 'accessing' }
ORActionRemoveTUnknownVariable >> incomingAccesses [ ^incomingAccesses
]

{ #category : 'accessing' }
ORActionRemoveTUnknownVariable >> incomingAccesses: aValue [ incomingAccesses := aValue
]

{ #category : 'accessing' }
ORActionRemoveTUnknownVariable >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveTUnknownVariable >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveTUnknownVariable >> name [ ^name
]

{ #category : 'accessing' }
ORActionRemoveTUnknownVariable >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRemoveTUnknownVariable >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveTUnknownVariable >> sourceAnchor: aValue [ sourceAnchor := aValue
]
