Class {
	#name : 'ORActionMoveTAnnotationInstance',
	#superclass : 'ORActionMove',
	#instVars : [
		'annotatedEntity',
		'annotationType'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionMoveTAnnotationInstance >> annotatedEntity [ ^annotatedEntity
]

{ #category : 'accessing' }
ORActionMoveTAnnotationInstance >> annotatedEntity: aValue [ annotatedEntity := aValue
]

{ #category : 'accessing' }
ORActionMoveTAnnotationInstance >> annotationType [ ^annotationType
]

{ #category : 'accessing' }
ORActionMoveTAnnotationInstance >> annotationType: aValue [ annotationType := aValue
]

{ #category : 'accessing' }
ORActionMoveTAnnotationInstance >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionMoveTAnnotationInstance >> attributes: aValue [ attributes := aValue
]
