Class {
	#name : 'ORActionRemoveTEnumValue',
	#superclass : 'ORActionRemoveNamedEntity',
	#instVars : [
		'parentEnum',
		'isStub',
		'sourceAnchor',
		'declaredType'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveTEnumValue >> declaredType [ ^declaredType
]

{ #category : 'accessing' }
ORActionRemoveTEnumValue >> declaredType: aValue [ declaredType := aValue
]

{ #category : 'accessing' }
ORActionRemoveTEnumValue >> incomingAccesses [ ^incomingAccesses
]

{ #category : 'accessing' }
ORActionRemoveTEnumValue >> incomingAccesses: aValue [ incomingAccesses := aValue
]

{ #category : 'accessing' }
ORActionRemoveTEnumValue >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveTEnumValue >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveTEnumValue >> name [ ^name
]

{ #category : 'accessing' }
ORActionRemoveTEnumValue >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRemoveTEnumValue >> parentEnum [ ^parentEnum
]

{ #category : 'accessing' }
ORActionRemoveTEnumValue >> parentEnum: aValue [ parentEnum := aValue
]

{ #category : 'accessing' }
ORActionRemoveTEnumValue >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveTEnumValue >> sourceAnchor: aValue [ sourceAnchor := aValue
]
