Class {
	#name : 'ORActionMoveTClass',
	#superclass : 'ORActionMoveNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionMoveTClass >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionMoveTClass >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionMoveTClass >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionMoveTClass >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionMoveTClass >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionMoveTClass >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionMoveTClass >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionMoveTClass >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionMoveTClass >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionMoveTClass >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionMoveTClass >> name [ ^name
]

{ #category : 'accessing' }
ORActionMoveTClass >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionMoveTClass >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionMoveTClass >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'accessing' }
ORActionMoveTClass >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionMoveTClass >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionMoveTClass >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionMoveTClass >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionMoveTClass >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionMoveTClass >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionMoveTClass >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionMoveTClass >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionMoveTClass >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionMoveTClass >> typedEntities: aValue [ typedEntities := aValue
]
