Class {
	#name : 'ORActionRemoveTPrimitiveType',
	#superclass : 'ORActionRemoveNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveTPrimitiveType >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionRemoveTPrimitiveType >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionRemoveTPrimitiveType >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveTPrimitiveType >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveTPrimitiveType >> name [ ^name
]

{ #category : 'accessing' }
ORActionRemoveTPrimitiveType >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRemoveTPrimitiveType >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveTPrimitiveType >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRemoveTPrimitiveType >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionRemoveTPrimitiveType >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionRemoveTPrimitiveType >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionRemoveTPrimitiveType >> typedEntities: aValue [ typedEntities := aValue
]
