Class {
	#name : 'ORActionRemoveJavaAnnotationInstance',
	#superclass : 'ORActionRemoveTAnnotationInstance',
	#instVars : [
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveJavaAnnotationInstance >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveJavaAnnotationInstance >> sourceAnchor: aValue [ sourceAnchor := aValue
]
