Class {
	#name : 'ORActionRenameTType',
	#superclass : 'ORActionRenameNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRenameTType >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionRenameTType >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionRenameTType >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRenameTType >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRenameTType >> name [ ^name
]

{ #category : 'accessing' }
ORActionRenameTType >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRenameTType >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRenameTType >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRenameTType >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionRenameTType >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionRenameTType >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionRenameTType >> typedEntities: aValue [ typedEntities := aValue
]
