Class {
	#name : 'ORActionMoveTException',
	#superclass : 'ORActionMoveNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionMoveTException >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionMoveTException >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> catchingEntities [ ^catchingEntities
]

{ #category : 'accessing' }
ORActionMoveTException >> catchingEntities: aValue [ catchingEntities := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionMoveTException >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> declaringEntities [ ^declaringEntities
]

{ #category : 'accessing' }
ORActionMoveTException >> declaringEntities: aValue [ declaringEntities := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionMoveTException >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionMoveTException >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionMoveTException >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> name [ ^name
]

{ #category : 'accessing' }
ORActionMoveTException >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionMoveTException >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionMoveTException >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionMoveTException >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionMoveTException >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> throwingEntities [ ^throwingEntities
]

{ #category : 'accessing' }
ORActionMoveTException >> throwingEntities: aValue [ throwingEntities := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionMoveTException >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionMoveTException >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionMoveTException >> typedEntities: aValue [ typedEntities := aValue
]
