Class {
	#name : 'ORActionRemoveTMethod',
	#superclass : 'ORActionRemoveNamedEntity',
	#instVars : [
		'parentType',
		'signature',
		'declaredType',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveTMethod >> accesses [ ^accesses
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> accesses: aValue [ accesses := aValue
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> declaredType [ ^declaredType
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> declaredType: aValue [ declaredType := aValue
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> implicitVariables [ ^implicitVariables
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> implicitVariables: aValue [ implicitVariables := aValue
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> incomingInvocations [ ^incomingInvocations
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> incomingInvocations: aValue [ incomingInvocations := aValue
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> localVariables [ ^localVariables
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> localVariables: aValue [ localVariables := aValue
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> name [ ^name
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> outgoingInvocations [ ^outgoingInvocations
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> outgoingInvocations: aValue [ outgoingInvocations := aValue
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> outgoingReferences [ ^outgoingReferences
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> outgoingReferences: aValue [ outgoingReferences := aValue
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> parameters [ ^parameters
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> parameters: aValue [ parameters := aValue
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> parentType [ ^parentType
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> parentType: aValue [ parentType := aValue
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> signature [ ^signature
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> signature: aValue [ signature := aValue
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveTMethod >> sourceAnchor: aValue [ sourceAnchor := aValue
]
