Class {
	#name : 'ORActionRemoveTType',
	#superclass : 'ORActionRemoveNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveTType >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionRemoveTType >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionRemoveTType >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveTType >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveTType >> name [ ^name
]

{ #category : 'accessing' }
ORActionRemoveTType >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRemoveTType >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveTType >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRemoveTType >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionRemoveTType >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionRemoveTType >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionRemoveTType >> typedEntities: aValue [ typedEntities := aValue
]
