Class {
	#name : 'ORActionRenameJavaEnum',
	#superclass : 'ORActionRenameTEnum',
	#instVars : [
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'methods',
		'visibility',
		'incomingImports',
		'receivingInvocations',
		'attributes',
		'comments',
		'imports',
		'superInheritances',
		'subInheritances'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRenameJavaEnum >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> types [ ^types
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionRenameJavaEnum >> visibility: aValue [ visibility := aValue
]
