Class {
	#name : 'ORActionMoveJavaEnumValue',
	#superclass : 'ORActionMoveTEnumValue',
	#instVars : [
		'annotationInstances',
		'receivingInvocations',
		'comments'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionMoveJavaEnumValue >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionMoveJavaEnumValue >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnumValue >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionMoveJavaEnumValue >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnumValue >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionMoveJavaEnumValue >> receivingInvocations: aValue [ receivingInvocations := aValue
]
