Class {
	#name : 'ORActionRemoveTEnum',
	#superclass : 'ORActionRemoveNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveTEnum >> enumValues [ ^enumValues
]

{ #category : 'accessing' }
ORActionRemoveTEnum >> enumValues: aValue [ enumValues := aValue
]

{ #category : 'accessing' }
ORActionRemoveTEnum >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionRemoveTEnum >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionRemoveTEnum >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveTEnum >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveTEnum >> name [ ^name
]

{ #category : 'accessing' }
ORActionRemoveTEnum >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRemoveTEnum >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveTEnum >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRemoveTEnum >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionRemoveTEnum >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionRemoveTEnum >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionRemoveTEnum >> typedEntities: aValue [ typedEntities := aValue
]
