Class {
	#name : 'ORActionRenameTMethod',
	#superclass : 'ORActionRenameNamedEntity',
	#instVars : [
		'parentType',
		'signature',
		'declaredType',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRenameTMethod >> accesses [ ^accesses
]

{ #category : 'accessing' }
ORActionRenameTMethod >> accesses: aValue [ accesses := aValue
]

{ #category : 'accessing' }
ORActionRenameTMethod >> declaredType [ ^declaredType
]

{ #category : 'accessing' }
ORActionRenameTMethod >> declaredType: aValue [ declaredType := aValue
]

{ #category : 'accessing' }
ORActionRenameTMethod >> implicitVariables [ ^implicitVariables
]

{ #category : 'accessing' }
ORActionRenameTMethod >> implicitVariables: aValue [ implicitVariables := aValue
]

{ #category : 'accessing' }
ORActionRenameTMethod >> incomingInvocations [ ^incomingInvocations
]

{ #category : 'accessing' }
ORActionRenameTMethod >> incomingInvocations: aValue [ incomingInvocations := aValue
]

{ #category : 'accessing' }
ORActionRenameTMethod >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRenameTMethod >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRenameTMethod >> localVariables [ ^localVariables
]

{ #category : 'accessing' }
ORActionRenameTMethod >> localVariables: aValue [ localVariables := aValue
]

{ #category : 'accessing' }
ORActionRenameTMethod >> name [ ^name
]

{ #category : 'accessing' }
ORActionRenameTMethod >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRenameTMethod >> outgoingInvocations [ ^outgoingInvocations
]

{ #category : 'accessing' }
ORActionRenameTMethod >> outgoingInvocations: aValue [ outgoingInvocations := aValue
]

{ #category : 'accessing' }
ORActionRenameTMethod >> outgoingReferences [ ^outgoingReferences
]

{ #category : 'accessing' }
ORActionRenameTMethod >> outgoingReferences: aValue [ outgoingReferences := aValue
]

{ #category : 'accessing' }
ORActionRenameTMethod >> parameters [ ^parameters
]

{ #category : 'accessing' }
ORActionRenameTMethod >> parameters: aValue [ parameters := aValue
]

{ #category : 'accessing' }
ORActionRenameTMethod >> parentType [ ^parentType
]

{ #category : 'accessing' }
ORActionRenameTMethod >> parentType: aValue [ parentType := aValue
]

{ #category : 'accessing' }
ORActionRenameTMethod >> signature [ ^signature
]

{ #category : 'accessing' }
ORActionRenameTMethod >> signature: aValue [ signature := aValue
]

{ #category : 'accessing' }
ORActionRenameTMethod >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRenameTMethod >> sourceAnchor: aValue [ sourceAnchor := aValue
]
