Class {
	#name : 'ORActionRemoveTImplicitVariable',
	#superclass : 'ORActionRemoveNamedEntity',
	#instVars : [
		'parentBehaviouralEntity',
		'isStub',
		'sourceAnchor',
		'declaredType'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveTImplicitVariable >> declaredType [ ^declaredType
]

{ #category : 'accessing' }
ORActionRemoveTImplicitVariable >> declaredType: aValue [ declaredType := aValue
]

{ #category : 'accessing' }
ORActionRemoveTImplicitVariable >> incomingAccesses [ ^incomingAccesses
]

{ #category : 'accessing' }
ORActionRemoveTImplicitVariable >> incomingAccesses: aValue [ incomingAccesses := aValue
]

{ #category : 'accessing' }
ORActionRemoveTImplicitVariable >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveTImplicitVariable >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveTImplicitVariable >> name [ ^name
]

{ #category : 'accessing' }
ORActionRemoveTImplicitVariable >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRemoveTImplicitVariable >> parentBehaviouralEntity [ ^parentBehaviouralEntity
]

{ #category : 'accessing' }
ORActionRemoveTImplicitVariable >> parentBehaviouralEntity: aValue [ parentBehaviouralEntity := aValue
]

{ #category : 'accessing' }
ORActionRemoveTImplicitVariable >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveTImplicitVariable >> sourceAnchor: aValue [ sourceAnchor := aValue
]
