Class {
	#name : 'ORActionRenameTParameterConcretization',
	#superclass : 'ORActionRename',
	#instVars : [
		'genericParameter',
		'concreteParameter',
		'next',
		'previous',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRenameTParameterConcretization >> concreteParameter [ ^concreteParameter
]

{ #category : 'accessing' }
ORActionRenameTParameterConcretization >> concreteParameter: aValue [ concreteParameter := aValue
]

{ #category : 'accessing' }
ORActionRenameTParameterConcretization >> genericParameter [ ^genericParameter
]

{ #category : 'accessing' }
ORActionRenameTParameterConcretization >> genericParameter: aValue [ genericParameter := aValue
]

{ #category : 'accessing' }
ORActionRenameTParameterConcretization >> next [ ^next
]

{ #category : 'accessing' }
ORActionRenameTParameterConcretization >> next: aValue [ next := aValue
]

{ #category : 'accessing' }
ORActionRenameTParameterConcretization >> previous [ ^previous
]

{ #category : 'accessing' }
ORActionRenameTParameterConcretization >> previous: aValue [ previous := aValue
]

{ #category : 'accessing' }
ORActionRenameTParameterConcretization >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRenameTParameterConcretization >> sourceAnchor: aValue [ sourceAnchor := aValue
]
