Class {
	#name : 'ORActionRenameTClass',
	#superclass : 'ORActionRenameNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRenameTClass >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionRenameTClass >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionRenameTClass >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionRenameTClass >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionRenameTClass >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionRenameTClass >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionRenameTClass >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRenameTClass >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRenameTClass >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionRenameTClass >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionRenameTClass >> name [ ^name
]

{ #category : 'accessing' }
ORActionRenameTClass >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRenameTClass >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionRenameTClass >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'accessing' }
ORActionRenameTClass >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRenameTClass >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRenameTClass >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionRenameTClass >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionRenameTClass >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionRenameTClass >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionRenameTClass >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionRenameTClass >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionRenameTClass >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionRenameTClass >> typedEntities: aValue [ typedEntities := aValue
]
