Class {
	#name : 'ORActionRemoveTClass',
	#superclass : 'ORActionRemoveNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveTClass >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionRemoveTClass >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionRemoveTClass >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionRemoveTClass >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionRemoveTClass >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionRemoveTClass >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionRemoveTClass >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveTClass >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveTClass >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionRemoveTClass >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionRemoveTClass >> name [ ^name
]

{ #category : 'accessing' }
ORActionRemoveTClass >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRemoveTClass >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionRemoveTClass >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'accessing' }
ORActionRemoveTClass >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveTClass >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRemoveTClass >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionRemoveTClass >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionRemoveTClass >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionRemoveTClass >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionRemoveTClass >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionRemoveTClass >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionRemoveTClass >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionRemoveTClass >> typedEntities: aValue [ typedEntities := aValue
]
