Class {
	#name : 'ORActionRemoveTPackage',
	#superclass : 'ORActionRemoveNamedEntity',
	#instVars : [
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveTPackage >> childEntities [ ^childEntities
]

{ #category : 'accessing' }
ORActionRemoveTPackage >> childEntities: aValue [ childEntities := aValue
]

{ #category : 'accessing' }
ORActionRemoveTPackage >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveTPackage >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveTPackage >> name [ ^name
]

{ #category : 'accessing' }
ORActionRemoveTPackage >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRemoveTPackage >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveTPackage >> sourceAnchor: aValue [ sourceAnchor := aValue
]
