Class {
	#name : 'ORActionMoveTEnum',
	#superclass : 'ORActionMoveNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionMoveTEnum >> enumValues [ ^enumValues
]

{ #category : 'accessing' }
ORActionMoveTEnum >> enumValues: aValue [ enumValues := aValue
]

{ #category : 'accessing' }
ORActionMoveTEnum >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionMoveTEnum >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionMoveTEnum >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionMoveTEnum >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionMoveTEnum >> name [ ^name
]

{ #category : 'accessing' }
ORActionMoveTEnum >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionMoveTEnum >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionMoveTEnum >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionMoveTEnum >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionMoveTEnum >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionMoveTEnum >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionMoveTEnum >> typedEntities: aValue [ typedEntities := aValue
]
