Class {
	#name : 'ORActionMoveTType',
	#superclass : 'ORActionMoveNamedEntity',
	#instVars : [
		'typeContainer',
		'isStub',
		'sourceAnchor'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionMoveTType >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionMoveTType >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionMoveTType >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionMoveTType >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionMoveTType >> name [ ^name
]

{ #category : 'accessing' }
ORActionMoveTType >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionMoveTType >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionMoveTType >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionMoveTType >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionMoveTType >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionMoveTType >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionMoveTType >> typedEntities: aValue [ typedEntities := aValue
]
