Class {
	#name : 'ORActionRenameTUnknownVariable',
	#superclass : 'ORActionRenameNamedEntity',
	#instVars : [
		'isStub',
		'sourceAnchor',
		'declaredType'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRenameTUnknownVariable >> declaredType [ ^declaredType
]

{ #category : 'accessing' }
ORActionRenameTUnknownVariable >> declaredType: aValue [ declaredType := aValue
]

{ #category : 'accessing' }
ORActionRenameTUnknownVariable >> incomingAccesses [ ^incomingAccesses
]

{ #category : 'accessing' }
ORActionRenameTUnknownVariable >> incomingAccesses: aValue [ incomingAccesses := aValue
]

{ #category : 'accessing' }
ORActionRenameTUnknownVariable >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRenameTUnknownVariable >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRenameTUnknownVariable >> name [ ^name
]

{ #category : 'accessing' }
ORActionRenameTUnknownVariable >> name: aValue [ name := aValue
]

{ #category : 'accessing' }
ORActionRenameTUnknownVariable >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRenameTUnknownVariable >> sourceAnchor: aValue [ sourceAnchor := aValue
]
