Class {
	#name : 'ORActionMoveTAnnotationType',
	#superclass : 'ORActionMove',
	#instVars : [
		'annotationTypesContainer'
	],
	#category : 'Orion-Actions',
	#package : 'Orion',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionMoveTAnnotationType >> annotationTypesContainer [ ^annotationTypesContainer
]

{ #category : 'accessing' }
ORActionMoveTAnnotationType >> annotationTypesContainer: aValue [ annotationTypesContainer := aValue
]

{ #category : 'accessing' }
ORActionMoveTAnnotationType >> instances [ ^instances
]

{ #category : 'accessing' }
ORActionMoveTAnnotationType >> instances: aValue [ instances := aValue
]
