"
I remove a FamixJavaParametricInterface in a MooseModel
I need the following properties of the  parametricinterface

-`mooseID`
-`mooseName`
-`cache`
-`entityAttributes`
-`mooseModel`
-`sourceAnchor`
-`annotationInstances`
-`types`
-`definedAnnotationTypes`
-`lowerBoundedWildcards`
-`upperBoundedWildcards`
-`concreteEntities`
-`generics`
-`typeContainer`
-`typedEntities`
-`isStub`
-`incomingReferences`
-`methods`
-`isClassSide`
-`isFinal`
-`visibility`
-`implementations`
-`incomingImports`
-`receivingInvocations`
-`parentPackage`
-`attributes`
-`comments`
-`imports`
-`superInheritances`
-`subInheritances`
-`concreteParameters`
-`concretizations`
-`genericParameters`
-`genericization`
"
Class {
	#name : 'ORActionRemoveJavaParametricInterface',
	#superclass : 'ORActionRemoveJava',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel',
		'sourceAnchor',
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'typeContainer',
		'typedEntities',
		'isStub',
		'incomingReferences',
		'methods',
		'isClassSide',
		'isFinal',
		'visibility',
		'implementations',
		'incomingImports',
		'receivingInvocations',
		'parentPackage',
		'attributes',
		'comments',
		'imports',
		'superInheritances',
		'subInheritances',
		'concreteParameters',
		'concretizations',
		'genericParameters',
		'genericization'
	],
	#category : 'Orion-Java-Actions',
	#package : 'Orion-Java',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> concreteParameters [ ^concreteParameters
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> concreteParameters: aValue [ concreteParameters := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> concretizations [ ^concretizations
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> concretizations: aValue [ concretizations := aValue
]

{ #category : 'method execution' }
ORActionRemoveJavaParametricInterface >> createVersionnedEntitySelector [ ^ #newParametricInterface
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> genericParameters [ ^genericParameters
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> genericParameters: aValue [ genericParameters := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> genericization [ ^genericization
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> genericization: aValue [ genericization := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> implementations [ ^implementations
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> implementations: aValue [ implementations := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> mooseName: aValue [ mooseName := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> parentPackage [ ^parentPackage
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> parentPackage: aValue [ parentPackage := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'method execution' }
ORActionRemoveJavaParametricInterface >> run [

	super run.
	entity mooseID: nil.
	entity mooseName: nil.
	entity cache: nil.
	entity entityAttributes: nil.
	entity mooseModel: nil.
	entity sourceAnchor: nil.
	entity annotationInstances: nil.
	entity types: nil.
	entity definedAnnotationTypes: nil.
	entity lowerBoundedWildcards: nil.
	entity upperBoundedWildcards: nil.
	entity concreteEntities: nil.
	entity generics: nil.
	entity typeContainer: nil.
	entity typedEntities: nil.
	entity isStub: nil.
	entity incomingReferences: nil.
	entity methods: nil.
	entity isClassSide: nil.
	entity isFinal: nil.
	entity visibility: nil.
	entity implementations: nil.
	entity incomingImports: nil.
	entity receivingInvocations: nil.
	entity parentPackage: nil.
	entity attributes: nil.
	entity comments: nil.
	entity imports: nil.
	entity superInheritances: nil.
	entity subInheritances: nil.
	entity concreteParameters: nil.
	entity concretizations: nil.
	entity genericParameters: nil.
	entity genericization: nil.

	self orionModel remove: (self orionModel versionLookup: self entity).

	^entity.
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> typedEntities: aValue [ typedEntities := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> types [ ^types
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricInterface >> visibility: aValue [ visibility := aValue
]
