Class {
	#name : 'ORActionMoveJavaInheritance',
	#superclass : 'ORActionMoveTInheritance',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel'
	],
	#category : 'Orion-Java-Move',
	#package : 'Orion-Java',
	#tag : 'Move'
}

{ #category : 'accessing' }
ORActionMoveJavaInheritance >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionMoveJavaInheritance >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaInheritance >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionMoveJavaInheritance >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaInheritance >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionMoveJavaInheritance >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaInheritance >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionMoveJavaInheritance >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaInheritance >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionMoveJavaInheritance >> mooseName: aValue [ mooseName := aValue
]
