Class {
	#name : 'ORActionMoveJavaImplementation',
	#superclass : 'ORActionMoveTImplementation',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel'
	],
	#category : 'Orion-Java-Move',
	#package : 'Orion-Java',
	#tag : 'Move'
}

{ #category : 'accessing' }
ORActionMoveJavaImplementation >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionMoveJavaImplementation >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaImplementation >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionMoveJavaImplementation >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaImplementation >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionMoveJavaImplementation >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaImplementation >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionMoveJavaImplementation >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaImplementation >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionMoveJavaImplementation >> mooseName: aValue [ mooseName := aValue
]
