Class {
	#name : 'ORActionMoveJavaParameterConcretization',
	#superclass : 'ORActionMoveTParameterConcretization',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel'
	],
	#category : 'Orion-Java-Move',
	#package : 'Orion-Java',
	#tag : 'Move'
}

{ #category : 'accessing' }
ORActionMoveJavaParameterConcretization >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionMoveJavaParameterConcretization >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaParameterConcretization >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionMoveJavaParameterConcretization >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaParameterConcretization >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionMoveJavaParameterConcretization >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaParameterConcretization >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionMoveJavaParameterConcretization >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaParameterConcretization >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionMoveJavaParameterConcretization >> mooseName: aValue [ mooseName := aValue
]
