Class {
	#name : 'ORActionMoveJavaComment',
	#superclass : 'ORActionMoveTComment',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel'
	],
	#category : 'Orion-Java-Move',
	#package : 'Orion-Java',
	#tag : 'Move'
}

{ #category : 'accessing' }
ORActionMoveJavaComment >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionMoveJavaComment >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaComment >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionMoveJavaComment >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaComment >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionMoveJavaComment >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaComment >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionMoveJavaComment >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaComment >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionMoveJavaComment >> mooseName: aValue [ mooseName := aValue
]
