"
I remove a FamixJavaParametricClass in a MooseModel
I need the following properties of the  parametricclass

-`mooseID`
-`mooseName`
-`cache`
-`entityAttributes`
-`mooseModel`
-`sourceAnchor`
-`annotationInstances`
-`types`
-`definedAnnotationTypes`
-`lowerBoundedWildcards`
-`upperBoundedWildcards`
-`concreteEntities`
-`generics`
-`typeContainer`
-`typedEntities`
-`isStub`
-`incomingReferences`
-`methods`
-`isAbstract`
-`isClassSide`
-`isFinal`
-`interfaceImplementations`
-`receivingInvocations`
-`attributes`
-`comments`
-`superInheritances`
-`subInheritances`
-`visibility`
-`incomingImports`
-`parentPackage`
-`imports`
-`concreteParameters`
-`concretizations`
-`genericParameters`
-`genericization`
"
Class {
	#name : 'ORActionRemoveJavaParametricClass',
	#superclass : 'ORActionRemoveNamedEntity',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel',
		'sourceAnchor',
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'typeContainer',
		'typedEntities',
		'isStub',
		'incomingReferences',
		'methods',
		'isAbstract',
		'isClassSide',
		'isFinal',
		'interfaceImplementations',
		'receivingInvocations',
		'attributes',
		'comments',
		'superInheritances',
		'subInheritances',
		'visibility',
		'incomingImports',
		'parentPackage',
		'imports',
		'concreteParameters',
		'concretizations',
		'genericParameters',
		'genericization'
	],
	#category : 'Orion-Java-Remove',
	#package : 'Orion-Java',
	#tag : 'Remove'
}

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> concreteParameters [ ^concreteParameters
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> concreteParameters: aValue [ concreteParameters := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> concretizations [ ^concretizations
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> concretizations: aValue [ concretizations := aValue
]

{ #category : 'method execution' }
ORActionRemoveJavaParametricClass >> createVersionnedEntitySelector [ ^ #newParametricClass
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> genericParameters [ ^genericParameters
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> genericParameters: aValue [ genericParameters := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> genericization [ ^genericization
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> genericization: aValue [ genericization := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> interfaceImplementations [ ^interfaceImplementations
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> interfaceImplementations: aValue [ interfaceImplementations := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> isAbstract [ ^isAbstract
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> isAbstract: aValue [ isAbstract := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> mooseName: aValue [ mooseName := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> parentPackage [ ^parentPackage
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> parentPackage: aValue [ parentPackage := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'method execution' }
ORActionRemoveJavaParametricClass >> run [

	super run.
	entity mooseID: nil.
	entity mooseName: nil.
	entity cache: nil.
	entity entityAttributes: nil.
	entity mooseModel: nil.
	entity sourceAnchor: nil.
	entity annotationInstances: nil.
	entity types: nil.
	entity definedAnnotationTypes: nil.
	entity lowerBoundedWildcards: nil.
	entity upperBoundedWildcards: nil.
	entity concreteEntities: nil.
	entity generics: nil.
	entity typeContainer: nil.
	entity typedEntities: nil.
	entity isStub: nil.
	entity incomingReferences: nil.
	entity methods: nil.
	entity isAbstract: nil.
	entity isClassSide: nil.
	entity isFinal: nil.
	entity interfaceImplementations: nil.
	entity receivingInvocations: nil.
	entity attributes: nil.
	entity comments: nil.
	entity superInheritances: nil.
	entity subInheritances: nil.
	entity visibility: nil.
	entity incomingImports: nil.
	entity parentPackage: nil.
	entity imports: nil.
	entity concreteParameters: nil.
	entity concretizations: nil.
	entity genericParameters: nil.
	entity genericization: nil.

	self orionModel remove: (self orionModel versionLookup: self entity).

	^entity.
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> typedEntities: aValue [ typedEntities := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> types [ ^types
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricClass >> visibility: aValue [ visibility := aValue
]
