"
I rename a new FamixJavaException in a MooseModel
I need the following properties of the new exception

-`annotationInstances`
-`types`
-`definedAnnotationTypes`
-`lowerBoundedWildcards`
-`upperBoundedWildcards`
-`concreteEntities`
-`generics`
-`isAbstract`
-`isClassSide`
-`isFinal`
-`interfaceImplementations`
-`visibility`
-`incomingImports`
-`parentPackage`
-`imports`
"
Class {
	#name : 'ORActionRenameJavaException',
	#superclass : 'ORActionRenameTException',
	#instVars : [
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'isAbstract',
		'isClassSide',
		'isFinal',
		'interfaceImplementations',
		'visibility',
		'incomingImports',
		'parentPackage',
		'imports'
	],
	#category : 'Orion-Java-Rename',
	#package : 'Orion-Java',
	#tag : 'Rename'
}

{ #category : 'accessing' }
ORActionRenameJavaException >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionRenameJavaException >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionRenameJavaException >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionRenameJavaException >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionRenameJavaException >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionRenameJavaException >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionRenameJavaException >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> interfaceImplementations [ ^interfaceImplementations
]

{ #category : 'accessing' }
ORActionRenameJavaException >> interfaceImplementations: aValue [ interfaceImplementations := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> isAbstract [ ^isAbstract
]

{ #category : 'accessing' }
ORActionRenameJavaException >> isAbstract: aValue [ isAbstract := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionRenameJavaException >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionRenameJavaException >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionRenameJavaException >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> parentPackage [ ^parentPackage
]

{ #category : 'accessing' }
ORActionRenameJavaException >> parentPackage: aValue [ parentPackage := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> types [ ^types
]

{ #category : 'accessing' }
ORActionRenameJavaException >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionRenameJavaException >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaException >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionRenameJavaException >> visibility: aValue [ visibility := aValue
]
