Class {
	#name : 'ORActionMoveJavaException',
	#superclass : 'ORActionMoveTException',
	#instVars : [
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'isAbstract',
		'isClassSide',
		'isFinal',
		'interfaceImplementations',
		'visibility',
		'incomingImports',
		'parentPackage',
		'imports'
	],
	#category : 'Orion-Java',
	#package : 'Orion-Java'
}

{ #category : 'accessing' }
ORActionMoveJavaException >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionMoveJavaException >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionMoveJavaException >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionMoveJavaException >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionMoveJavaException >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionMoveJavaException >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionMoveJavaException >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> interfaceImplementations [ ^interfaceImplementations
]

{ #category : 'accessing' }
ORActionMoveJavaException >> interfaceImplementations: aValue [ interfaceImplementations := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> isAbstract [ ^isAbstract
]

{ #category : 'accessing' }
ORActionMoveJavaException >> isAbstract: aValue [ isAbstract := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionMoveJavaException >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionMoveJavaException >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionMoveJavaException >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> parentPackage [ ^parentPackage
]

{ #category : 'accessing' }
ORActionMoveJavaException >> parentPackage: aValue [ parentPackage := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> types [ ^types
]

{ #category : 'accessing' }
ORActionMoveJavaException >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionMoveJavaException >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaException >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionMoveJavaException >> visibility: aValue [ visibility := aValue
]
