"
I add a FamixJavaParametricMethod in a MooseModel
I need the following properties of the  parametricmethod

-`mooseID`
-`mooseName`
-`cache`
-`entityAttributes`
-`mooseModel`
-`sourceAnchor`
-`annotationInstances`
-`types`
-`definedAnnotationTypes`
-`isSynchronized`
-`isAbstract`
-`isClassSide`
-`isFinal`
-`kind`
-`visibility`
-`incomingImports`
-`parentType`
-`signature`
-`incomingInvocations`
-`declaredType`
-`implicitVariables`
-`localVariables`
-`parameters`
-`isStub`
-`accesses`
-`outgoingInvocations`
-`outgoingReferences`
-`comments`
-`caughtExceptions`
-`declaredExceptions`
-`thrownExceptions`
-`concreteParameters`
-`concretizations`
-`genericParameters`
-`genericization`
"
Class {
	#name : 'ORActionAddJavaParametricMethod',
	#superclass : 'ORActionAddJava',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel',
		'sourceAnchor',
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'isSynchronized',
		'isAbstract',
		'isClassSide',
		'isFinal',
		'kind',
		'visibility',
		'incomingImports',
		'parentType',
		'signature',
		'incomingInvocations',
		'declaredType',
		'implicitVariables',
		'localVariables',
		'parameters',
		'isStub',
		'accesses',
		'outgoingInvocations',
		'outgoingReferences',
		'comments',
		'caughtExceptions',
		'declaredExceptions',
		'thrownExceptions',
		'concreteParameters',
		'concretizations',
		'genericParameters',
		'genericization'
	],
	#category : 'Orion-Java-Actions',
	#package : 'Orion-Java',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> accesses [ ^accesses
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> accesses: aValue [ accesses := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> caughtExceptions [ ^caughtExceptions
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> caughtExceptions: aValue [ caughtExceptions := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> concreteParameters [ ^concreteParameters
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> concreteParameters: aValue [ concreteParameters := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> concretizations [ ^concretizations
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> concretizations: aValue [ concretizations := aValue
]

{ #category : 'method execution' }
ORActionAddJavaParametricMethod >> createVersionnedEntitySelector [ ^ #newParametricMethod
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> declaredExceptions [ ^declaredExceptions
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> declaredExceptions: aValue [ declaredExceptions := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> declaredType [ ^declaredType
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> declaredType: aValue [ declaredType := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> genericParameters [ ^genericParameters
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> genericParameters: aValue [ genericParameters := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> genericization [ ^genericization
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> genericization: aValue [ genericization := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> implicitVariables [ ^implicitVariables
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> implicitVariables: aValue [ implicitVariables := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> incomingInvocations [ ^incomingInvocations
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> incomingInvocations: aValue [ incomingInvocations := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> isAbstract [ ^isAbstract
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> isAbstract: aValue [ isAbstract := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> isSynchronized [ ^isSynchronized
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> isSynchronized: aValue [ isSynchronized := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> kind [ ^kind
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> kind: aValue [ kind := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> localVariables [ ^localVariables
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> localVariables: aValue [ localVariables := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> mooseName: aValue [ mooseName := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> outgoingInvocations [ ^outgoingInvocations
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> outgoingInvocations: aValue [ outgoingInvocations := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> outgoingReferences [ ^outgoingReferences
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> outgoingReferences: aValue [ outgoingReferences := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> parameters [ ^parameters
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> parameters: aValue [ parameters := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> parentType [ ^parentType
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> parentType: aValue [ parentType := aValue
]

{ #category : 'method execution' }
ORActionAddJavaParametricMethod >> run [

	super run.
	entity mooseID: self mooseID.
	entity mooseName: self mooseName.
	entity cache: self cache.
	entity entityAttributes: self entityAttributes.
	entity mooseModel: self mooseModel.
	entity sourceAnchor: self sourceAnchor.
	entity annotationInstances: self annotationInstances.
	entity types: self types.
	entity definedAnnotationTypes: self definedAnnotationTypes.
	entity isSynchronized: self isSynchronized.
	entity isAbstract: self isAbstract.
	entity isClassSide: self isClassSide.
	entity isFinal: self isFinal.
	entity kind: self kind.
	entity visibility: self visibility.
	entity incomingImports: self incomingImports.
	entity parentType: self parentType.
	entity signature: self signature.
	entity incomingInvocations: self incomingInvocations.
	entity declaredType: self declaredType.
	entity implicitVariables: self implicitVariables.
	entity localVariables: self localVariables.
	entity parameters: self parameters.
	entity isStub: self isStub.
	entity accesses: self accesses.
	entity outgoingInvocations: self outgoingInvocations.
	entity outgoingReferences: self outgoingReferences.
	entity comments: self comments.
	entity caughtExceptions: self caughtExceptions.
	entity declaredExceptions: self declaredExceptions.
	entity thrownExceptions: self thrownExceptions.
	entity concreteParameters: self concreteParameters.
	entity concretizations: self concretizations.
	entity genericParameters: self genericParameters.
	entity genericization: self genericization.

	^entity.
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> signature [ ^signature
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> signature: aValue [ signature := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> thrownExceptions [ ^thrownExceptions
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> thrownExceptions: aValue [ thrownExceptions := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> types [ ^types
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionAddJavaParametricMethod >> visibility: aValue [ visibility := aValue
]
