"
I remove a new FamixJavaException in a MooseModel
I need the following properties of the new exception

-`annotationInstances`
-`types`
-`definedAnnotationTypes`
-`lowerBoundedWildcards`
-`upperBoundedWildcards`
-`concreteEntities`
-`generics`
-`isAbstract`
-`isClassSide`
-`isFinal`
-`interfaceImplementations`
-`visibility`
-`incomingImports`
-`parentPackage`
-`imports`
"
Class {
	#name : 'ORActionRemoveJavaException',
	#superclass : 'ORActionRemoveTException',
	#instVars : [
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'isAbstract',
		'isClassSide',
		'isFinal',
		'interfaceImplementations',
		'visibility',
		'incomingImports',
		'parentPackage',
		'imports'
	],
	#category : 'Orion-Java',
	#package : 'Orion-Java'
}

{ #category : 'accessing' }
ORActionRemoveJavaException >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> interfaceImplementations [ ^interfaceImplementations
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> interfaceImplementations: aValue [ interfaceImplementations := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> isAbstract [ ^isAbstract
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> isAbstract: aValue [ isAbstract := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> parentPackage [ ^parentPackage
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> parentPackage: aValue [ parentPackage := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> types [ ^types
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionRemoveJavaException >> visibility: aValue [ visibility := aValue
]
