"
I add a FamixJavaException in a MooseModel
I need the following properties of the  exception

-`mooseID`
-`mooseName`
-`cache`
-`entityAttributes`
-`mooseModel`
-`sourceAnchor`
-`annotationInstances`
-`types`
-`definedAnnotationTypes`
-`lowerBoundedWildcards`
-`upperBoundedWildcards`
-`concreteEntities`
-`generics`
-`typeContainer`
-`typedEntities`
-`isStub`
-`incomingReferences`
-`methods`
-`isAbstract`
-`isClassSide`
-`isFinal`
-`interfaceImplementations`
-`receivingInvocations`
-`attributes`
-`comments`
-`superInheritances`
-`subInheritances`
-`visibility`
-`incomingImports`
-`parentPackage`
-`imports`
-`catchingEntities`
-`declaringEntities`
-`throwingEntities`
"
Class {
	#name : 'ORActionAddJavaException',
	#superclass : 'ORActionAddNamedEntity',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel',
		'sourceAnchor',
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'typeContainer',
		'typedEntities',
		'isStub',
		'incomingReferences',
		'methods',
		'isAbstract',
		'isClassSide',
		'isFinal',
		'interfaceImplementations',
		'receivingInvocations',
		'attributes',
		'comments',
		'superInheritances',
		'subInheritances',
		'visibility',
		'incomingImports',
		'parentPackage',
		'imports',
		'catchingEntities',
		'declaringEntities',
		'throwingEntities'
	],
	#category : 'Orion-Java-Add',
	#package : 'Orion-Java',
	#tag : 'Add'
}

{ #category : 'accessing' }
ORActionAddJavaException >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionAddJavaException >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionAddJavaException >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionAddJavaException >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> catchingEntities [ ^catchingEntities
]

{ #category : 'accessing' }
ORActionAddJavaException >> catchingEntities: aValue [ catchingEntities := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionAddJavaException >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionAddJavaException >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'method execution' }
ORActionAddJavaException >> createVersionnedEntitySelector [ ^ #newException
]

{ #category : 'accessing' }
ORActionAddJavaException >> declaringEntities [ ^declaringEntities
]

{ #category : 'accessing' }
ORActionAddJavaException >> declaringEntities: aValue [ declaringEntities := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionAddJavaException >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionAddJavaException >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionAddJavaException >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionAddJavaException >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionAddJavaException >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionAddJavaException >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> interfaceImplementations [ ^interfaceImplementations
]

{ #category : 'accessing' }
ORActionAddJavaException >> interfaceImplementations: aValue [ interfaceImplementations := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> isAbstract [ ^isAbstract
]

{ #category : 'accessing' }
ORActionAddJavaException >> isAbstract: aValue [ isAbstract := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionAddJavaException >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionAddJavaException >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionAddJavaException >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionAddJavaException >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionAddJavaException >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionAddJavaException >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionAddJavaException >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionAddJavaException >> mooseName: aValue [ mooseName := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> parentPackage [ ^parentPackage
]

{ #category : 'accessing' }
ORActionAddJavaException >> parentPackage: aValue [ parentPackage := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionAddJavaException >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'method execution' }
ORActionAddJavaException >> run [

	super run.
	entity mooseID: self mooseID.
	entity mooseName: self mooseName.
	entity cache: self cache.
	entity entityAttributes: self entityAttributes.
	entity mooseModel: self mooseModel.
	entity sourceAnchor: self sourceAnchor.
	entity annotationInstances: self annotationInstances.
	entity types: self types.
	entity definedAnnotationTypes: self definedAnnotationTypes.
	entity lowerBoundedWildcards: self lowerBoundedWildcards.
	entity upperBoundedWildcards: self upperBoundedWildcards.
	entity concreteEntities: self concreteEntities.
	entity generics: self generics.
	entity typeContainer: self typeContainer.
	entity typedEntities: self typedEntities.
	entity isStub: self isStub.
	entity incomingReferences: self incomingReferences.
	entity methods: self methods.
	entity isAbstract: self isAbstract.
	entity isClassSide: self isClassSide.
	entity isFinal: self isFinal.
	entity interfaceImplementations: self interfaceImplementations.
	entity receivingInvocations: self receivingInvocations.
	entity attributes: self attributes.
	entity comments: self comments.
	entity superInheritances: self superInheritances.
	entity subInheritances: self subInheritances.
	entity visibility: self visibility.
	entity incomingImports: self incomingImports.
	entity parentPackage: self parentPackage.
	entity imports: self imports.
	entity catchingEntities: self catchingEntities.
	entity declaringEntities: self declaringEntities.
	entity throwingEntities: self throwingEntities.

	^entity.
]

{ #category : 'accessing' }
ORActionAddJavaException >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionAddJavaException >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionAddJavaException >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionAddJavaException >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> throwingEntities [ ^throwingEntities
]

{ #category : 'accessing' }
ORActionAddJavaException >> throwingEntities: aValue [ throwingEntities := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionAddJavaException >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionAddJavaException >> typedEntities: aValue [ typedEntities := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> types [ ^types
]

{ #category : 'accessing' }
ORActionAddJavaException >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionAddJavaException >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionAddJavaException >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionAddJavaException >> visibility: aValue [ visibility := aValue
]
