"
I add a FamixJavaParametricInterface in a MooseModel
I need the following properties of the  parametricinterface

-`mooseID`
-`mooseName`
-`cache`
-`entityAttributes`
-`mooseModel`
-`sourceAnchor`
-`annotationInstances`
-`types`
-`definedAnnotationTypes`
-`lowerBoundedWildcards`
-`upperBoundedWildcards`
-`concreteEntities`
-`generics`
-`typeContainer`
-`typedEntities`
-`isStub`
-`incomingReferences`
-`methods`
-`isClassSide`
-`isFinal`
-`visibility`
-`implementations`
-`incomingImports`
-`receivingInvocations`
-`parentPackage`
-`attributes`
-`comments`
-`imports`
-`superInheritances`
-`subInheritances`
-`concreteParameters`
-`concretizations`
-`genericParameters`
-`genericization`
"
Class {
	#name : 'ORActionAddJavaParametricInterface',
	#superclass : 'ORActionAddJava',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel',
		'sourceAnchor',
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'typeContainer',
		'typedEntities',
		'isStub',
		'incomingReferences',
		'methods',
		'isClassSide',
		'isFinal',
		'visibility',
		'implementations',
		'incomingImports',
		'receivingInvocations',
		'parentPackage',
		'attributes',
		'comments',
		'imports',
		'superInheritances',
		'subInheritances',
		'concreteParameters',
		'concretizations',
		'genericParameters',
		'genericization'
	],
	#category : 'Orion-Java-Actions',
	#package : 'Orion-Java',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> concreteParameters [ ^concreteParameters
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> concreteParameters: aValue [ concreteParameters := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> concretizations [ ^concretizations
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> concretizations: aValue [ concretizations := aValue
]

{ #category : 'method execution' }
ORActionAddJavaParametricInterface >> createVersionnedEntitySelector [ ^ #newParametricInterface
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> genericParameters [ ^genericParameters
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> genericParameters: aValue [ genericParameters := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> genericization [ ^genericization
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> genericization: aValue [ genericization := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> implementations [ ^implementations
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> implementations: aValue [ implementations := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> mooseName: aValue [ mooseName := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> parentPackage [ ^parentPackage
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> parentPackage: aValue [ parentPackage := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'method execution' }
ORActionAddJavaParametricInterface >> run [

	super run.
	entity mooseID: self mooseID.
	entity mooseName: self mooseName.
	entity cache: self cache.
	entity entityAttributes: self entityAttributes.
	entity mooseModel: self mooseModel.
	entity sourceAnchor: self sourceAnchor.
	entity annotationInstances: self annotationInstances.
	entity types: self types.
	entity definedAnnotationTypes: self definedAnnotationTypes.
	entity lowerBoundedWildcards: self lowerBoundedWildcards.
	entity upperBoundedWildcards: self upperBoundedWildcards.
	entity concreteEntities: self concreteEntities.
	entity generics: self generics.
	entity typeContainer: self typeContainer.
	entity typedEntities: self typedEntities.
	entity isStub: self isStub.
	entity incomingReferences: self incomingReferences.
	entity methods: self methods.
	entity isClassSide: self isClassSide.
	entity isFinal: self isFinal.
	entity visibility: self visibility.
	entity implementations: self implementations.
	entity incomingImports: self incomingImports.
	entity receivingInvocations: self receivingInvocations.
	entity parentPackage: self parentPackage.
	entity attributes: self attributes.
	entity comments: self comments.
	entity imports: self imports.
	entity superInheritances: self superInheritances.
	entity subInheritances: self subInheritances.
	entity concreteParameters: self concreteParameters.
	entity concretizations: self concretizations.
	entity genericParameters: self genericParameters.
	entity genericization: self genericization.

	^entity.
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> typedEntities: aValue [ typedEntities := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> types [ ^types
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionAddJavaParametricInterface >> visibility: aValue [ visibility := aValue
]
