Class {
	#name : 'ORActionMoveJavaConcretization',
	#superclass : 'ORActionMoveTConcretization',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel'
	],
	#category : 'Orion-Java-Move',
	#package : 'Orion-Java',
	#tag : 'Move'
}

{ #category : 'accessing' }
ORActionMoveJavaConcretization >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionMoveJavaConcretization >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaConcretization >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionMoveJavaConcretization >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaConcretization >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionMoveJavaConcretization >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaConcretization >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionMoveJavaConcretization >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaConcretization >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionMoveJavaConcretization >> mooseName: aValue [ mooseName := aValue
]
