Class {
	#name : 'ORActionMoveJavaAccess',
	#superclass : 'ORActionMoveTAccess',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel'
	],
	#category : 'Orion-Java-Move',
	#package : 'Orion-Java',
	#tag : 'Move'
}

{ #category : 'accessing' }
ORActionMoveJavaAccess >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionMoveJavaAccess >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaAccess >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionMoveJavaAccess >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaAccess >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionMoveJavaAccess >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaAccess >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionMoveJavaAccess >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaAccess >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionMoveJavaAccess >> mooseName: aValue [ mooseName := aValue
]
