"
I remove a FamixJavaParametricMethod in a MooseModel
I need the following properties of the  parametricmethod

-`mooseID`
-`mooseName`
-`cache`
-`entityAttributes`
-`mooseModel`
-`sourceAnchor`
-`annotationInstances`
-`types`
-`definedAnnotationTypes`
-`isSynchronized`
-`isAbstract`
-`isClassSide`
-`isFinal`
-`kind`
-`visibility`
-`incomingImports`
-`parentType`
-`signature`
-`incomingInvocations`
-`declaredType`
-`implicitVariables`
-`localVariables`
-`parameters`
-`isStub`
-`accesses`
-`outgoingInvocations`
-`outgoingReferences`
-`comments`
-`caughtExceptions`
-`declaredExceptions`
-`thrownExceptions`
-`concreteParameters`
-`concretizations`
-`genericParameters`
-`genericization`
"
Class {
	#name : 'ORActionRemoveJavaParametricMethod',
	#superclass : 'ORActionRemoveJava',
	#instVars : [
		'sourceAnchor',
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'isSynchronized',
		'isAbstract',
		'isClassSide',
		'isFinal',
		'kind',
		'visibility',
		'incomingImports',
		'parentType',
		'signature',
		'incomingInvocations',
		'declaredType',
		'implicitVariables',
		'localVariables',
		'parameters',
		'isStub',
		'accesses',
		'outgoingInvocations',
		'outgoingReferences',
		'comments',
		'caughtExceptions',
		'declaredExceptions',
		'thrownExceptions',
		'concreteParameters',
		'concretizations',
		'genericParameters',
		'genericization'
	],
	#category : 'Orion-Java-Actions',
	#package : 'Orion-Java',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> accesses [ ^accesses
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> accesses: aValue [ accesses := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> caughtExceptions [ ^caughtExceptions
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> caughtExceptions: aValue [ caughtExceptions := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> concreteParameters [ ^concreteParameters
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> concreteParameters: aValue [ concreteParameters := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> concretizations [ ^concretizations
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> concretizations: aValue [ concretizations := aValue
]

{ #category : 'method execution' }
ORActionRemoveJavaParametricMethod >> createVersionnedEntitySelector [ ^ #newParametricMethod
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> declaredExceptions [ ^declaredExceptions
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> declaredExceptions: aValue [ declaredExceptions := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> declaredType [ ^declaredType
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> declaredType: aValue [ declaredType := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> genericParameters [ ^genericParameters
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> genericParameters: aValue [ genericParameters := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> genericization [ ^genericization
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> genericization: aValue [ genericization := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> implicitVariables [ ^implicitVariables
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> implicitVariables: aValue [ implicitVariables := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> incomingInvocations [ ^incomingInvocations
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> incomingInvocations: aValue [ incomingInvocations := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> isAbstract [ ^isAbstract
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> isAbstract: aValue [ isAbstract := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> isSynchronized [ ^isSynchronized
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> isSynchronized: aValue [ isSynchronized := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> kind [ ^kind
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> kind: aValue [ kind := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> localVariables [ ^localVariables
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> localVariables: aValue [ localVariables := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> outgoingInvocations [ ^outgoingInvocations
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> outgoingInvocations: aValue [ outgoingInvocations := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> outgoingReferences [ ^outgoingReferences
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> outgoingReferences: aValue [ outgoingReferences := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> parameters [ ^parameters
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> parameters: aValue [ parameters := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> parentType [ ^parentType
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> parentType: aValue [ parentType := aValue
]

{ #category : 'method execution' }
ORActionRemoveJavaParametricMethod >> run [

	super run.
	entity sourceAnchor: nil.
	entity annotationInstances: nil.
	entity types: nil.
	entity definedAnnotationTypes: nil.
	entity isSynchronized: nil.
	entity isAbstract: nil.
	entity isClassSide: nil.
	entity isFinal: nil.
	entity kind: nil.
	entity visibility: nil.
	entity incomingImports: nil.
	entity parentType: nil.
	entity signature: nil.
	entity incomingInvocations: nil.
	entity declaredType: nil.
	entity implicitVariables: nil.
	entity localVariables: nil.
	entity parameters: nil.
	entity isStub: nil.
	entity accesses: nil.
	entity outgoingInvocations: nil.
	entity outgoingReferences: nil.
	entity comments: nil.
	entity caughtExceptions: nil.
	entity declaredExceptions: nil.
	entity thrownExceptions: nil.
	entity concreteParameters: nil.
	entity concretizations: nil.
	entity genericParameters: nil.
	entity genericization: nil.

	self orionModel remove: (self orionModel versionLookup: self entity).

	^entity.
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> signature [ ^signature
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> signature: aValue [ signature := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> thrownExceptions [ ^thrownExceptions
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> thrownExceptions: aValue [ thrownExceptions := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> types [ ^types
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionRemoveJavaParametricMethod >> visibility: aValue [ visibility := aValue
]
