Class {
	#name : 'ORActionMoveJavaInvocation',
	#superclass : 'ORActionMoveTInvocation',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel'
	],
	#category : 'Orion-Java-Move',
	#package : 'Orion-Java',
	#tag : 'Move'
}

{ #category : 'accessing' }
ORActionMoveJavaInvocation >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionMoveJavaInvocation >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaInvocation >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionMoveJavaInvocation >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaInvocation >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionMoveJavaInvocation >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaInvocation >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionMoveJavaInvocation >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaInvocation >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionMoveJavaInvocation >> mooseName: aValue [ mooseName := aValue
]
