"
I remove a FamixJavaClass in a MooseModel
I need the following properties of the  class

-`mooseID`
-`mooseName`
-`cache`
-`entityAttributes`
-`mooseModel`
-`sourceAnchor`
-`annotationInstances`
-`types`
-`definedAnnotationTypes`
-`lowerBoundedWildcards`
-`upperBoundedWildcards`
-`concreteEntities`
-`generics`
-`typeContainer`
-`typedEntities`
-`isStub`
-`incomingReferences`
-`methods`
-`isAbstract`
-`isClassSide`
-`isFinal`
-`interfaceImplementations`
-`receivingInvocations`
-`attributes`
-`comments`
-`superInheritances`
-`subInheritances`
-`visibility`
-`incomingImports`
-`parentPackage`
-`imports`
"
Class {
	#name : 'ORActionRemoveJavaClass',
	#superclass : 'ORActionRemoveNamedEntity',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel',
		'sourceAnchor',
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'typeContainer',
		'typedEntities',
		'isStub',
		'incomingReferences',
		'methods',
		'isAbstract',
		'isClassSide',
		'isFinal',
		'interfaceImplementations',
		'receivingInvocations',
		'attributes',
		'comments',
		'superInheritances',
		'subInheritances',
		'visibility',
		'incomingImports',
		'parentPackage',
		'imports'
	],
	#category : 'Orion-Java-Remove',
	#package : 'Orion-Java',
	#tag : 'Remove'
}

{ #category : 'accessing' }
ORActionRemoveJavaClass >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'method execution' }
ORActionRemoveJavaClass >> createVersionnedEntitySelector [ ^ #newClass
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> interfaceImplementations [ ^interfaceImplementations
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> interfaceImplementations: aValue [ interfaceImplementations := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isAbstract [ ^isAbstract
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isAbstract: aValue [ isAbstract := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> mooseName: aValue [ mooseName := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> parentPackage [ ^parentPackage
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> parentPackage: aValue [ parentPackage := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'method execution' }
ORActionRemoveJavaClass >> run [

	super run.
	entity mooseID: nil.
	entity mooseName: nil.
	entity cache: nil.
	entity entityAttributes: nil.
	entity mooseModel: nil.
	entity sourceAnchor: nil.
	entity annotationInstances: nil.
	entity types: nil.
	entity definedAnnotationTypes: nil.
	entity lowerBoundedWildcards: nil.
	entity upperBoundedWildcards: nil.
	entity concreteEntities: nil.
	entity generics: nil.
	entity typeContainer: nil.
	entity typedEntities: nil.
	entity isStub: nil.
	entity incomingReferences: nil.
	entity methods: nil.
	entity isAbstract: nil.
	entity isClassSide: nil.
	entity isFinal: nil.
	entity interfaceImplementations: nil.
	entity receivingInvocations: nil.
	entity attributes: nil.
	entity comments: nil.
	entity superInheritances: nil.
	entity subInheritances: nil.
	entity visibility: nil.
	entity incomingImports: nil.
	entity parentPackage: nil.
	entity imports: nil.

	self orionModel remove: (self orionModel versionLookup: self entity).

	^entity.
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> typedEntities: aValue [ typedEntities := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> types [ ^types
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> visibility: aValue [ visibility := aValue
]
