Class {
	#name : 'ORActionRenameJavaType',
	#superclass : 'ORActionRenameTType',
	#instVars : [
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'methods'
	],
	#category : 'Orion-Java',
	#package : 'Orion-Java'
}

{ #category : 'accessing' }
ORActionRenameJavaType >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionRenameJavaType >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaType >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionRenameJavaType >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaType >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionRenameJavaType >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaType >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionRenameJavaType >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaType >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionRenameJavaType >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaType >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionRenameJavaType >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaType >> types [ ^types
]

{ #category : 'accessing' }
ORActionRenameJavaType >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaType >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionRenameJavaType >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]
