Class {
	#name : 'ORActionRemoveJavaClass',
	#superclass : 'ORActionRemoveTClass',
	#instVars : [
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'isAbstract',
		'isClassSide',
		'isFinal',
		'interfaceImplementations',
		'visibility',
		'incomingImports',
		'parentPackage',
		'imports'
	],
	#category : 'Orion-Java',
	#package : 'Orion-Java'
}

{ #category : 'accessing' }
ORActionRemoveJavaClass >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> interfaceImplementations [ ^interfaceImplementations
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> interfaceImplementations: aValue [ interfaceImplementations := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isAbstract [ ^isAbstract
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isAbstract: aValue [ isAbstract := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> parentPackage [ ^parentPackage
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> parentPackage: aValue [ parentPackage := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> types [ ^types
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionRemoveJavaClass >> visibility: aValue [ visibility := aValue
]
