"
I remove a new FamixJavaEnum in a MooseModel
I need the following properties of the new enum

-`annotationInstances`
-`types`
-`definedAnnotationTypes`
-`lowerBoundedWildcards`
-`upperBoundedWildcards`
-`concreteEntities`
-`generics`
-`methods`
-`visibility`
-`incomingImports`
-`receivingInvocations`
-`attributes`
-`comments`
-`imports`
-`superInheritances`
-`subInheritances`
"
Class {
	#name : 'ORActionRemoveJavaEnum',
	#superclass : 'ORActionRemoveTEnum',
	#instVars : [
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'methods',
		'visibility',
		'incomingImports',
		'receivingInvocations',
		'attributes',
		'comments',
		'imports',
		'superInheritances',
		'subInheritances'
	],
	#category : 'Orion-Java',
	#package : 'Orion-Java'
}

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> types [ ^types
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionRemoveJavaEnum >> visibility: aValue [ visibility := aValue
]
