"
I move a new FamixJavaEnum in a MooseModel
I need the following properties of the new enum

-`annotationInstances`
-`types`
-`definedAnnotationTypes`
-`lowerBoundedWildcards`
-`upperBoundedWildcards`
-`concreteEntities`
-`generics`
-`methods`
-`visibility`
-`incomingImports`
-`receivingInvocations`
-`attributes`
-`comments`
-`imports`
-`superInheritances`
-`subInheritances`
"
Class {
	#name : 'ORActionMoveJavaEnum',
	#superclass : 'ORActionMoveTEnum',
	#instVars : [
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'methods',
		'visibility',
		'incomingImports',
		'receivingInvocations',
		'attributes',
		'comments',
		'imports',
		'superInheritances',
		'subInheritances'
	],
	#category : 'Orion-Java-Move',
	#package : 'Orion-Java',
	#tag : 'Move'
}

{ #category : 'accessing' }
ORActionMoveJavaEnum >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> types [ ^types
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionMoveJavaEnum >> visibility: aValue [ visibility := aValue
]
