Class {
	#name : 'ORActionMoveJavaSourceLanguage',
	#superclass : 'ORActionMoveTSourceLanguage',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel'
	],
	#category : 'Orion-Java-Move',
	#package : 'Orion-Java',
	#tag : 'Move'
}

{ #category : 'accessing' }
ORActionMoveJavaSourceLanguage >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionMoveJavaSourceLanguage >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaSourceLanguage >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionMoveJavaSourceLanguage >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaSourceLanguage >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionMoveJavaSourceLanguage >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaSourceLanguage >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionMoveJavaSourceLanguage >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaSourceLanguage >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionMoveJavaSourceLanguage >> mooseName: aValue [ mooseName := aValue
]
