Class {
	#name : 'ORActionMoveJavaImport',
	#superclass : 'ORActionMoveTImport',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel'
	],
	#category : 'Orion-Java-Move',
	#package : 'Orion-Java',
	#tag : 'Move'
}

{ #category : 'accessing' }
ORActionMoveJavaImport >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionMoveJavaImport >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaImport >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionMoveJavaImport >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaImport >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionMoveJavaImport >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaImport >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionMoveJavaImport >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionMoveJavaImport >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionMoveJavaImport >> mooseName: aValue [ mooseName := aValue
]
