"
I add a FamixJavaParametricClass in a MooseModel
I need the following properties of the  parametricclass

-`mooseID`
-`mooseName`
-`cache`
-`entityAttributes`
-`mooseModel`
-`sourceAnchor`
-`annotationInstances`
-`types`
-`definedAnnotationTypes`
-`lowerBoundedWildcards`
-`upperBoundedWildcards`
-`concreteEntities`
-`generics`
-`typeContainer`
-`typedEntities`
-`isStub`
-`incomingReferences`
-`methods`
-`isAbstract`
-`isClassSide`
-`isFinal`
-`interfaceImplementations`
-`receivingInvocations`
-`attributes`
-`comments`
-`superInheritances`
-`subInheritances`
-`visibility`
-`incomingImports`
-`parentPackage`
-`imports`
-`concreteParameters`
-`concretizations`
-`genericParameters`
-`genericization`
"
Class {
	#name : 'ORActionAddJavaParametricClass',
	#superclass : 'ORActionAddJava',
	#instVars : [
		'mooseID',
		'mooseName',
		'cache',
		'entityAttributes',
		'mooseModel',
		'sourceAnchor',
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'typeContainer',
		'typedEntities',
		'isStub',
		'incomingReferences',
		'methods',
		'isAbstract',
		'isClassSide',
		'isFinal',
		'interfaceImplementations',
		'receivingInvocations',
		'attributes',
		'comments',
		'superInheritances',
		'subInheritances',
		'visibility',
		'incomingImports',
		'parentPackage',
		'imports',
		'concreteParameters',
		'concretizations',
		'genericParameters',
		'genericization'
	],
	#category : 'Orion-Java-Actions',
	#package : 'Orion-Java',
	#tag : 'Actions'
}

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> attributes [ ^attributes
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> attributes: aValue [ attributes := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> cache [ ^cache
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> cache: aValue [ cache := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> comments [ ^comments
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> comments: aValue [ comments := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> concreteParameters [ ^concreteParameters
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> concreteParameters: aValue [ concreteParameters := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> concretizations [ ^concretizations
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> concretizations: aValue [ concretizations := aValue
]

{ #category : 'method execution' }
ORActionAddJavaParametricClass >> createVersionnedEntitySelector [ ^ #newParametricClass
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> entityAttributes [ ^entityAttributes
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> entityAttributes: aValue [ entityAttributes := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> genericParameters [ ^genericParameters
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> genericParameters: aValue [ genericParameters := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> genericization [ ^genericization
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> genericization: aValue [ genericization := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> incomingReferences [ ^incomingReferences
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> incomingReferences: aValue [ incomingReferences := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> interfaceImplementations [ ^interfaceImplementations
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> interfaceImplementations: aValue [ interfaceImplementations := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> isAbstract [ ^isAbstract
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> isAbstract: aValue [ isAbstract := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> isStub [ ^isStub
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> isStub: aValue [ isStub := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> methods [ ^methods
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> methods: aValue [ methods := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> mooseID [ ^mooseID
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> mooseID: aValue [ mooseID := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> mooseModel [ ^mooseModel
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> mooseModel: aValue [ mooseModel := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> mooseName [ ^mooseName
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> mooseName: aValue [ mooseName := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> parentPackage [ ^parentPackage
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> parentPackage: aValue [ parentPackage := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> receivingInvocations [ ^receivingInvocations
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> receivingInvocations: aValue [ receivingInvocations := aValue
]

{ #category : 'method execution' }
ORActionAddJavaParametricClass >> run [

	super run.
	entity mooseID: self mooseID.
	entity mooseName: self mooseName.
	entity cache: self cache.
	entity entityAttributes: self entityAttributes.
	entity mooseModel: self mooseModel.
	entity sourceAnchor: self sourceAnchor.
	entity annotationInstances: self annotationInstances.
	entity types: self types.
	entity definedAnnotationTypes: self definedAnnotationTypes.
	entity lowerBoundedWildcards: self lowerBoundedWildcards.
	entity upperBoundedWildcards: self upperBoundedWildcards.
	entity concreteEntities: self concreteEntities.
	entity generics: self generics.
	entity typeContainer: self typeContainer.
	entity typedEntities: self typedEntities.
	entity isStub: self isStub.
	entity incomingReferences: self incomingReferences.
	entity methods: self methods.
	entity isAbstract: self isAbstract.
	entity isClassSide: self isClassSide.
	entity isFinal: self isFinal.
	entity interfaceImplementations: self interfaceImplementations.
	entity receivingInvocations: self receivingInvocations.
	entity attributes: self attributes.
	entity comments: self comments.
	entity superInheritances: self superInheritances.
	entity subInheritances: self subInheritances.
	entity visibility: self visibility.
	entity incomingImports: self incomingImports.
	entity parentPackage: self parentPackage.
	entity imports: self imports.
	entity concreteParameters: self concreteParameters.
	entity concretizations: self concretizations.
	entity genericParameters: self genericParameters.
	entity genericization: self genericization.

	^entity.
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> sourceAnchor [ ^sourceAnchor
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> sourceAnchor: aValue [ sourceAnchor := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> subInheritances [ ^subInheritances
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> subInheritances: aValue [ subInheritances := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> superInheritances [ ^superInheritances
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> superInheritances: aValue [ superInheritances := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> typeContainer [ ^typeContainer
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> typeContainer: aValue [ typeContainer := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> typedEntities [ ^typedEntities
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> typedEntities: aValue [ typedEntities := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> types [ ^types
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionAddJavaParametricClass >> visibility: aValue [ visibility := aValue
]
