"
I rename a new FamixJavaClass in a MooseModel
I need the following properties of the new class

-`annotationInstances`
-`types`
-`definedAnnotationTypes`
-`lowerBoundedWildcards`
-`upperBoundedWildcards`
-`concreteEntities`
-`generics`
-`isAbstract`
-`isClassSide`
-`isFinal`
-`interfaceImplementations`
-`visibility`
-`incomingImports`
-`parentPackage`
-`imports`
"
Class {
	#name : 'ORActionRenameJavaClass',
	#superclass : 'ORActionRenameTClass',
	#instVars : [
		'annotationInstances',
		'types',
		'definedAnnotationTypes',
		'lowerBoundedWildcards',
		'upperBoundedWildcards',
		'concreteEntities',
		'generics',
		'isAbstract',
		'isClassSide',
		'isFinal',
		'interfaceImplementations',
		'visibility',
		'incomingImports',
		'parentPackage',
		'imports'
	],
	#category : 'Orion-Java',
	#package : 'Orion-Java'
}

{ #category : 'accessing' }
ORActionRenameJavaClass >> annotationInstances [ ^annotationInstances
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> annotationInstances: aValue [ annotationInstances := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> concreteEntities [ ^concreteEntities
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> concreteEntities: aValue [ concreteEntities := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> definedAnnotationTypes [ ^definedAnnotationTypes
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> definedAnnotationTypes: aValue [ definedAnnotationTypes := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> generics [ ^generics
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> generics: aValue [ generics := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> imports [ ^imports
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> imports: aValue [ imports := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> incomingImports [ ^incomingImports
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> incomingImports: aValue [ incomingImports := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> interfaceImplementations [ ^interfaceImplementations
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> interfaceImplementations: aValue [ interfaceImplementations := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> isAbstract [ ^isAbstract
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> isAbstract: aValue [ isAbstract := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> isClassSide [ ^isClassSide
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> isClassSide: aValue [ isClassSide := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> isFinal [ ^isFinal
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> isFinal: aValue [ isFinal := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> lowerBoundedWildcards [ ^lowerBoundedWildcards
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> lowerBoundedWildcards: aValue [ lowerBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> parentPackage [ ^parentPackage
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> parentPackage: aValue [ parentPackage := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> types [ ^types
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> types: aValue [ types := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> upperBoundedWildcards [ ^upperBoundedWildcards
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> upperBoundedWildcards: aValue [ upperBoundedWildcards := aValue
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> visibility [ ^visibility
]

{ #category : 'accessing' }
ORActionRenameJavaClass >> visibility: aValue [ visibility := aValue
]
