Class {
	#name : 'ORActionRenameTMethodTest',
	#superclass : 'ORActionRenameNamedEntityTest',
	#category : 'Orion-Tests-Actions',
	#package : 'Orion-Tests',
	#tag : 'Actions'
}

{ #category : 'running' }
ORActionRenameTMethodTest >> setUpAction [ action := ORActionRenameTMethod new orionModel: modelV2; parentType: nil; signature: nil; declaredType: nil; isStub: nil; sourceAnchor: nil; yourself.
]
