Class {
	#name : 'ORActionMoveJavaAnnotationTypeTest',
	#superclass : 'ORActionMoveJavaTest',
	#category : 'Orion-Tests-Java',
	#package : 'Orion-Tests',
	#tag : 'Java'
}

{ #category : 'running' }
ORActionMoveJavaAnnotationTypeTest >> setUpAction [ action := ORActionMoveJavaAnnotationType new orionModel: modelV2; sourceAnchor: nil; name: nil; annotationInstances: nil; types: nil; definedAnnotationTypes: nil; lowerBoundedWildcards: nil; upperBoundedWildcards: nil; concreteEntities: nil; generics: nil; typeContainer: nil; typedEntities: nil; isStub: nil; incomingReferences: nil; methods: nil; visibility: nil; implementations: nil; parentPackage: nil; attributes: nil; comments: nil; superInheritances: nil; subInheritances: nil; yourself.
]
