Class {
	#name : 'ORActionMoveTAnnotationTypeAttributeTest',
	#superclass : 'ORActionMoveNamedEntityTest',
	#category : 'Orion-Tests-Actions',
	#package : 'Orion-Tests',
	#tag : 'Actions'
}

{ #category : 'running' }
ORActionMoveTAnnotationTypeAttributeTest >> setUpAction [ action := ORActionMoveTAnnotationTypeAttribute new orionModel: modelV2; parentType: nil; isStub: nil; sourceAnchor: nil; declaredType: nil; yourself.
]
