Class {
	#name : 'ORActionMoveTImplementationTest',
	#superclass : 'ORActionMoveTest',
	#category : 'Orion-Tests-Actions',
	#package : 'Orion-Tests',
	#tag : 'Actions'
}

{ #category : 'running' }
ORActionMoveTImplementationTest >> setUpAction [ action := ORActionMoveTImplementation new orionModel: modelV2; implementingClass: nil; interface: nil; next: nil; previous: nil; sourceAnchor: nil; yourself.
]
