Class {
	#name : 'ORActionMoveJavaAttributeTest',
	#superclass : 'ORActionMoveJavaTest',
	#category : 'Orion-Tests-Java-Model',
	#package : 'Orion-Tests',
	#tag : 'Java-Model'
}

{ #category : 'running' }
ORActionMoveJavaAttributeTest >> setUpAction [ action := ORActionMoveJavaAttribute new orionModel: modelV2; annotationInstances: nil; receivingInvocations: nil; isTransient: nil; isVolatile: nil; isClassSide: nil; isFinal: nil; visibility: nil; comments: nil; yourself.
]
